"""add excuses.name_id

Revision ID: 248ed72e1e11
Revises: 91dcace38064
Create Date: 2026-08-19 03:58:25.091400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248ed72e1e11'
down_revision = '91dcace38064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'names', ['name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excuses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name_id')

    # ### end Alembic commands ###
